{% set name = "libgit2" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 701a5086a968a46f25e631941b99fc23e4755ca2c56f59371ce1d94b9a0cc643

build:
  number: 1
  run_exports:
    # SONAME is based on minor version
    - {{ pin_subpackage("libgit2", max_pin="x.x") }}

requirements:
  build:
    - cmake
    - ninja
    - pkg-config      # [not win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - msinttypes      # [win]
    - openssl         # [not win]
    - libiconv        # [osx]
    - pcre2  # [unix]
    - curl
    - libssh2
    - zlib

test:
  commands:
    - test -f $PREFIX/include/git2.h                 # [not win]
    - if not exist %LIBRARY_INC%\\git2.h exit 1      # [win]
    - test -f $PREFIX/lib/libgit2${SHLIB_EXT}        # [unix]
    - if not exist %LIBRARY_LIB%\\git2.lib exit 1    # [win]
    - if not exist %LIBRARY_BIN%\\git2.dll exit 1    # [win]

about:
  home: https://libgit2.github.com
  license: GPL-2.0-only WITH GCC-exception-2.0
  license_file: COPYING
  summary: libgit2 is a portable, pure C implementation of the Git core methods provided as a re-entrant linkable library with a solid API, allowing you to write native speed custom Git applications in any language which supports C bindings.

  # The remaining entries in this section are optional, but recommended
  description: |
    libgit2 is a portable, pure C implementation of the Git core methods
    provided as a re-entrant linkable library with a solid API, allowing
    you to write native speed custom Git applications in any language
    which supports C bindings.

extra:
  recipe-maintainers:
    - shadowwalkersb
    - xhochy
